### ISSUE TITLE
Incorrect link in "Are you a package author / maintainer?" card on index.md?

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/peer-review-guide#137]
Again I know this is all under construction but I think the link in this card:

https://github.com/pyOpenSci/contributing-guide/blob/b7e7d80d6eeb582fcb4f346a2d8421f70ff507df/index.md?plain=1#L58

```
:::{grid-item-card}
:link: software-peer-review-guide/reviewer-guide

:link-type: doc
:class-header: bg-light

Are you a package author / maintainer? ✨
^^^

Learn how to submit a package for peer review with pyOpenSci.
:::
```

should instead be
```
:link: software-peer-review-guide/author-guide
```

Happy to fix with a PR if so

**Comment by lwasser** [comment]
please submit a PR if you wish. 
or i can too... i noticed the landing page is rendering funky again. 

I think today i'm going to rename the repo as well to peer-review-guide as that is what this document really is.

**Comment by NickleDave** [comment]
@lwasser can you assign to me? I'll fix the link this afternoon

**Comment by lwasser** [comment]
The syntax of the landing page had a lot of issues [so i fixed it just now ](https://www.pyopensci.org/peer-review-guide/https://www.pyopensci.org/peer-review-guide/ )- 
there were also a lot of broken links on that page and across the pages so i fixed those as well. finally CI needed a bit of love so now each PR will check for links and we are starting from GREEN. 

When i change a link in the future i'll try to get that redirect working properly to atleast fix the immediate need to find and destroy broken links. If this works now we can close this but i'll leave it to you to close.

**Comment by NickleDave** [comment]
Worked for me! Closing
