### ISSUE TITLE
Fix Broken Links in contributor guide

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/peer-review-guide#90]
Jupyter book link checker is returning false posities so i tried [linkchecker](https://github.com/linkchecker/linkchecker) and i see about 20 broken links to fix.

********
If the book link checker is not working let's figure it out through this issue. 
pr #110 adds a link checker to the build. [Here you can see all of the broken links](https://github.com/pyOpenSci/contributing-guide/actions/runs/3101380604/jobs/5022676736) that it is finding. 

We could use help if someone has time to fix these broken links via a pr. You could submit the pr against the branch that I opened a pr `add-link-checker` or you could submit to main and i can build locally to test. many thanks in advance. 

* [Here is the contributing guide online](https://www.pyopensci.org/contributing-guide/intro.html)
* [Here is an issue that i posted in the Jupyter Forum to figure out why their link checker](https://github.com/orgs/executablebooks/discussions/827) is giving me unexpected broken link results. It could be that we use html proofer instead here. i've had ongoing issues with their link checker

**Comment by Athene-ai** [comment]
I am interested

**Comment by lwasser** [comment]
hi there @Athene-ai let's focus on one issue at a time! would you prefer to work on the website issue or this one? Please let me know that and when you think you can work on it (and if you need any guidance) and i'll add your name to the appropriate issue!!

**Comment by Athene-ai** [comment]
Hi @lwasser I am interested in website issues and I can work now with guidance 

Let me know ;-)

**Comment by lwasser** [comment]
hi @Athene-ai So i have a very discrete thing that you can work in IF you wish to! 
If you want, [you can look at this pr](https://github.com/pyOpenSci/contributing-guide/pull/110)

Now I don't know what your  background is here so please ask questions if what I say below doesn't make sense. 
[Here i added CI to check the guide for broken links. ](https://github.com/pyOpenSci/contributing-guide/pull/110). We won't want to merge that PR until all of the links are fixed. 

So, if you watned to, you could fork that repo, and look at the [results of the action here](https://github.com/pyOpenSci/contributing-guide/actions/runs/3154939565/jobs/5133092774#step:7:19). And fix links. You can do as many or as few as you wish. 

And you can ping me if you have questions.
I will be offline for the most part for the next three days but back online on monday.

Let me know if this sounds doable OR if it is confusing OR if it's just not a task you want to work on!
Thank you for being here!

**Comment by Athene-ai** [comment]
Hi @lwasser !

Thansk for assign me this wonderful task!

I will take  look at it 😉

**Comment by lwasser** [comment]
@Athene-ai wonderful. please let me know if you have any questions.

**Comment by Athene-ai** [comment]
@lwasser sure

**Comment by lwasser** [comment]
Ok this has been done! via #142 and a few other pr's submitted by others. closing!
